### ISSUE TITLE
Error with using the docker 

### ISSUE THREAD

**Issue by ZhyGao** [ins-amu/tvb-pipeline#7]
Hi, sorry to interrupt you.
I have pulled the image maedoc/tvb-make and placed the data as your instruction.  Run the docker/run file as bellow.
`/data/gzy/tvb-pipeline_na/tvb-pipeline-master/docker/run SUBJECT=linyingxiu T1=data/T1.mgz DWI=data/dwi.mif fs-recon conn`
But I get the error with the subject. I don't know why, can you help me?
![1693989479206](https://github.com/ins-amu/tvb-pipeline/assets/39367799/f8898bde-3e2e-4cb1-be38-93e1d59a5944)

**Comment by maedoc** [comment]
hi, thanks for your interest.  the `maedoc/tvb-make` image is not up to date.  I can try to push the new image in the next week or so.
